### ISSUE TITLE
GoogleAnalytics is deprecated

### ISSUE THREAD

**Issue by b00f** [pactus-project/docs#14]
WARN  deprecated: .Site.GoogleAnalytics was deprecated in Hugo v0.120.0 and will be removed in a future release. Use .Site.Config.Services.GoogleAnalytics.ID instead.

**Comment by Ja7ad** [comment]
We use new way:

![image](https://github.com/pactus-project/docs/assets/56496801/55177ebd-6934-469f-8a07-bdff8200f970)
