### ISSUE TITLE
Utilize pngquant for image (png) optimization

### ISSUE THREAD

**Issue by b00f** [pactus-project/docs#5]
Utilize pngquant for the image optimization. Please check `pactus.org` repository for how to do it at [here](https://github.com/pactus-project/pactus.org/blob/eb97b6b1058e8e957190e3c998ff39eef6326f29/.github/workflows/deploy.yml#L26C20-L26C21).

**Comment by Ja7ad** [comment]
We can use https://github.com/imgbot instead ci.

**Comment by b00f** [comment]
Fixed at #16
